/**
 * Purchase Service
 * ──────────────────
 * Generación automática de pedidos a proveedores cuando insumos críticos
 * caen bajo el umbral. Agrupa por proveedor para reducir overhead.
 */

import { prisma } from "../prisma.js";
import { logger } from "../utils/logger.js";
import { inventoryService } from "./inventory.service.js";

class PurchaseService {
  /**
   * Detecta insumos en estado crítico cuyo proveedor permite auto-pedido,
   * agrupa por proveedor y genera Purchase Orders en estado DRAFT.
   * Devuelve las POs creadas para revisión humana antes de SENT.
   */
  async runAutoRestock(restaurantId: string): Promise<{ created: any[]; skipped: any[] }> {
    const critical = await inventoryService.getCriticalStock(restaurantId);
    const skipped: any[] = [];
    const eligibleByProvider = new Map<string, typeof critical>();

    for (const ing of critical) {
      if (!ing.supplier || !ing.supplier.autoOrderEnabled) {
        skipped.push({ ingredient: ing.name, reason: "supplier_no_autoorder" });
        continue;
      }
      const list = eligibleByProvider.get(ing.supplier.id) ?? [];
      list.push(ing);
      eligibleByProvider.set(ing.supplier.id, list);
    }

    const created: any[] = [];
    for (const [supplierId, ings] of eligibleByProvider) {
      // Skip if there's already a DRAFT or SENT PO for this supplier (avoid duplicates)
      const open = await prisma.purchaseOrder.findFirst({
        where: { restaurantId, supplierId, status: { in: ["DRAFT", "SENT", "PARTIAL"] } }
      });
      if (open) {
        skipped.push({ supplier: supplierId, reason: "open_po_exists", poId: open.id });
        continue;
      }

      let subtotal = 0;
      const lines = ings.map(i => {
        const qty = Math.max(0.1, i.optimalStock - i.currentStock);
        const unitCost = i.costPerUnitCents;
        subtotal += Math.round(qty * unitCost);
        return {
          ingredientId: i.id,
          qty,
          unit: i.unit,
          unitCostCents: unitCost
        };
      });

      const po = await prisma.purchaseOrder.create({
        data: {
          restaurantId,
          supplierId,
          status: "DRAFT",
          autoGenerated: true,
          subtotalCents: subtotal,
          taxCents: Math.round(subtotal * 0.18 / 1.18), // assume prices include IGV
          totalCents: subtotal,
          notes: "Generada automáticamente · stock crítico",
          lines: { create: lines }
        },
        include: { lines: true, supplier: true }
      });
      created.push(po);
      logger.info({ poId: po.id, supplier: po.supplier.name, lines: lines.length }, "Auto-PO created");
    }

    return { created, skipped };
  }

  /**
   * Mark PO as SENT (after manual review).
   */
  async markSent(poId: string) {
    return prisma.purchaseOrder.update({
      where: { id: poId },
      data: { status: "SENT", sentAt: new Date() }
    });
  }

  /**
   * Receive a purchase order (full or partial).
   * Adds stock and creates expiration lots if applicable.
   */
  async receive(poId: string, receivedLines: { lineId: string; qtyReceived: number; expirationDate?: string }[], userId: string) {
    const po = await prisma.purchaseOrder.findUnique({
      where: { id: poId },
      include: { lines: { include: { ingredient: true } } }
    });
    if (!po) throw new Error("po_not_found");

    let allReceived = true;

    for (const rl of receivedLines) {
      const line = po.lines.find(l => l.id === rl.lineId);
      if (!line) continue;
      const newReceived = line.qtyReceived + rl.qtyReceived;
      await prisma.purchaseOrderLine.update({
        where: { id: line.id },
        data: { qtyReceived: newReceived }
      });

      // Add stock + expiration lot
      await inventoryService.addStock({
        ingredientId: line.ingredientId,
        qty: rl.qtyReceived,
        unitCostCents: line.unitCostCents,
        type: "PURCHASE",
        refType: "PURCHASE_ORDER",
        refId: po.id,
        expirationDate: rl.expirationDate ? new Date(rl.expirationDate) : undefined,
        userId,
        notes: `PO ${po.id.slice(-8)}`
      });

      if (newReceived < line.qty) allReceived = false;
    }

    return prisma.purchaseOrder.update({
      where: { id: poId },
      data: {
        status: allReceived ? "RECEIVED" : "PARTIAL",
        receivedAt: allReceived ? new Date() : undefined
      },
      include: { lines: true, supplier: true }
    });
  }
}

export const purchaseService = new PurchaseService();
